// react-slickdeals/src/App.js
import React, { useEffect, useState } from "react";
import "./App.css";

function App() {
  const [data, setData] = useState([]);

  useEffect(() => {
    fetch("http://localhost:4000/")
      .then((res) => {
        return res.json();
      })
      .then((result) => setData(result));
  }, []);

  return (
    <div className="slickdeal-container">
      {data.map((i) => {
        return (
          <div key={i.id} className="item-image">
            <img src={i.imagePath} alt={i.name} id={i.id} />
            <div id={i.id}>{i.name}</div>
          </div>
        );
      })}
    </div>
  );
}

export default App;

// angular-slickdeals/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  listOfDeals = [];

  constructor(private http: HttpClient) { }

  ngOnInit() {
    this.getDeals();
  }
  getDeals() {
    return this.http.get<[{}]>('http://localhost:4000/').subscribe(data => this.listOfDeals = data);
  }
}

<div>
  <div *ngIf="listOfDeals.length > 0" class="deals-container">
    <div *ngFor="let item of listOfDeals" class="name-image">
      <img [src]="item.imagePath" alt="item.name" />
      <p>{{ item.name }}</p>
    </div>
  </div>
</div>
